FROM node:20-alpine

# Установка pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Копирование файлов зависимостей
COPY package.json pnpm-lock.yaml ./

# Установка зависимостей
RUN pnpm install

# Копирование остального кода
COPY . .

# Отключение телеметрии
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

# Запуск в dev режиме
CMD ["pnpm", "dev"]
